### ISSUE TITLE
swarm-cli-docker: automated build

### ISSUE THREAD

**Issue by puja108** [giantswarm/swarm-cli-docker#2]
We should turn this into an automated build inthe giantswarm Docker Hub account, I don't have the rights to access that repo though.

**Comment by marians** [comment]
Maybe @webwurst can do that for us.

**Comment by webwurst** [comment]
I don't know why, but I can. And did:
https://hub.docker.com/r/giantswarm/swarm-cli/

Are you ok with the name? I left out "-docker" since everything on the hub is docker.

**Comment by puja108** [comment]
Thanks
